import = ["/Users/imarmole/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
# family = "BlexMono Nerd Font"
family = "FiraCode Nerd Font"
# family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
style = "Italic"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleMaximized"
key = "Return"
mods = "Super"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.95
startup_mode = "Maximized"

[window.dimensions]
columns = 180
lines = 50

[window.padding]
x = 5
y = 2
